build:
  number: 0

package:
  name: idba
  version: "1.1.2"

source:
  fn: idba-1.1.2.tar.gz
  url: https://github.com/loneknightpy/idba/releases/download/1.1.2/idba-1.1.2.tar.gz
  md5: 0f0efa1534c7f15ae4bf64473a7709a4

requirements:
  build:
    - python
    - gcc
    
